"""add creado_en to lotes

Revision ID: 4442923089c9
Revises: 38cc0ca07ee8
Create Date: 2025-06-13 21:08:04.318998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4442923089c9"
down_revision: Union[str, None] = "38cc0ca07ee8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lotes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "creado_en",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lotes", schema=None) as batch_op:
        batch_op.drop_column("creado_en")

    # ### end Alembic commands ###
