"""initial schema

Revision ID: f3621d8cde35
Revises: 
Create Date: 2025-06-16 18:09:59.623804

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3621d8cde35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medicamentos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("principio_activo", sa.String(length=120), nullable=False),
        sa.Column("laboratorio", sa.String(length=120), nullable=True),
        sa.Column(
            "presentacion",
            sa.Enum(
                "TABLETA", "CAPSULA", "JARABE", "CREMA", "SOLUCION", name="presentacion"
            ),
            nullable=False,
        ),
        sa.Column("concentracion", sa.String(length=50), nullable=True),
        sa.Column("forma_farmaceutica", sa.String(length=50), nullable=True),
        sa.Column("via_administracion", sa.String(length=50), nullable=True),
        sa.Column("indicaciones", sa.String(length=255), nullable=True),
        sa.Column("contraindicaciones", sa.String(length=255), nullable=True),
        sa.Column("condiciones_almacenamiento", sa.String(length=255), nullable=True),
        sa.Column("imagen_url", sa.String(length=255), nullable=True),
        sa.Column("precio_venta", sa.Float(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("nombre_completo", sa.String(length=120), nullable=False),
        sa.Column("dni", sa.String(length=12), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("celular", sa.String(length=15), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column(
            "rol",
            sa.Enum(
                "ADMIN", "CAJERO", "AUDITOR", "ALMACENERO", "FARMACEUTICO", name="rol"
            ),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.CheckConstraint("username GLOB '[A-Za-z0-9]*'", name="chk_username_alnum"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dni"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "lotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("medicamento_id", sa.Integer(), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["medicamento_id"], ["medicamentos.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "movimientos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo", sa.Enum("ENTRADA", "SALIDA", name="tipomovimiento"), nullable=False
        ),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("motivo", sa.String(length=120), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["lote_id"], ["lotes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movimientos")
    op.drop_table("lotes")
    op.drop_table("usuarios")
    op.drop_table("medicamentos")
    # ### end Alembic commands ###
